global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'talentai-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Prometheus metrics from FastAPI app
    scrape_interval: 5s
    metrics_path: /
    params:
      format: ['prometheus']
    
  - job_name: 'talentai-api'
    static_configs:
      - targets: ['host.docker.internal:8001']  # FastAPI /metrics endpoint
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  # Optional: system metrics
    scrape_interval: 10s